# Konfigurasi GitHub Pages
theme: jekyll-theme-cayman
title: Maafin Aku
description: Halaman permintaan maaf lucu & imut buat pacar
baseurl: "/maaf"
url: "https://BangZaky0029.github.io"

# Pengaturan SEO
lang: id
author: Maafin Aku Project

# Pengaturan lainnya
markdown: kramdown
plugins:
  - jekyll-seo-tag